version: '3.2'

networks:
  tb-net:
    driver: bridge

services:
  tb-zk:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
      - 9090:8080
      - 2888:2888
      - 3888:3888
    environment:
      - ZOO_LOG4J_PROP="INFO,CONSOLE"
      - ALLOW_ANONYMOUS_LOGIN=yes
    hostname: zookeeper
    networks:
      tb-net:
        aliases:
          - zookeeper
  tb-cl:
    image: yandex/clickhouse-server
    depends_on:
      - tb-zk
    hostname: clickhouse
    networks:
      tb-net:
        aliases:
          - clickhouse
    entrypoint: /bin/bash
    command: [ "./wait-for-it.sh", "-t", "10", "zookeeper:2181", "--", "/entrypoint.sh" ]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./metrika.xml:/etc/metrika.xml
    ports:
      - 8123:8123
      - 9000:9000

